version: '3.8'

services:
  web:
    build: 
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - ENVIRONMENT=development
    env_file:
      - .env.dev
    volumes:
      - .:/app  # Mount current directory for hot reload
      - /app/__pycache__  # Exclude pycache from volume
      - /app/.pytest_cache  # Exclude pytest cache
    command: flask run --host=0.0.0.0 --port=8000 --debug --reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: